
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_cast
 - force_try
 - identifier_name
 - void_return
 
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
 - EComApp
 - EComAppTests
 - EComAppUITests
 
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 
 # parameterized rules can be customized from this configuration file
line_length:
 - 200



